version: "3.8"
services:
  review-tracker:
    build: .
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      # Set this to your MongoDB Atlas connection string in a .env file or CI/CD secret
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      # Comma-separated list of allowed origins (UI URLs). Example:
      # https://review-tracker.vinishchoudhary.com,https://www.review-tracker.vinishchoudhary.com,http://localhost:5173
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}
      # Optional: override server.port inside the container
      - SERVER_PORT=${SERVER_PORT:-8080}
      # Optional: JVM flags (e.g., memory)
      - JAVA_OPTS=${JAVA_OPTS:-}
    restart: unless-stopped
