spring:
  application:
    name: review-tracker-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/reviewtracker
      auto-index-creation: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
